- name: Update system_units
  script: ../files/ensure_system_units_have_version.sh {{ openshift.common.service_type }} {{ openshift.common.deployment_type }} {{ g_new_version }}

- name: Verifying the correct version was configured
  command: grep {{ verify_upgrade_version }} {{ item }}
  with_items:
    - /etc/sysconfig/openvswitch
    - /etc/sysconfig/{{ openshift.common.service_type }}*
  when: verify_upgrade_version is defined
